Repository xbehave/xbehave.net, pull requests merged in 2018-09, with the labels that each got.

#476 upgrade packages (no functional effect in resulting xbehave packages)
  src/Xbehave.Core/Xbehave.Core.csproj
  src/Xbehave.Execution/Xbehave.Execution.csproj
  targets/Targets.csproj
  tests/Xbehave.Test/Xbehave.Test.csproj
Labels: build

#478 add usage for IgnoreXunitAnalyzersRule1013Attribute
  src/Xbehave.Core/BackgroundAttribute.cs
Labels: build

#479 rename disposable object param name
  src/Xbehave.Core/DisposableExtensions.cs
Labels: breaking

#480 add Microsoft.CodeQuality.Analyzers
  src/Xbehave.Core/Xbehave.Core.csproj
  src/Xbehave.Execution/Xbehave.Execution.csproj
  src/Xbehave.Execution/Xbehave.Execution.ruleset
Labels: build

#481 update contribution guidelines
  CONTRIBUTING.md
Labels: docs

#484 upgrade build and test packages
  targets/Targets.csproj
  tests/Xbehave.Test/Xbehave.Test.csproj
Labels: build

#485 upgrade Bullseye to 1.3.0
  targets/Targets.csproj
Labels: build
